database.jdbc_url_sqlsrv: "jdbc:sqlserver://192.168.100.92:1433;DatabaseName=ContactManagerDB;User=gwUser;Password=Gu1d3W1r32020"
database.jdbc_url_h2: "jdbc:h2:file:/tmp/guidewire/ContactManagerDatabase;CACHE_SIZE=32000"
suite.url_suite_cc: "http://localhost:8080/cc"
suite.url_suite_pc: "http://localhost:8180/pc"
suite.url_suite_ab: "http://localhost:8280/ab"
suite.url_suite_bc: "http://localhost:8580/bc"
